-- Cashier customer permissions are granted in `prisma/seed.ts` (seedRbac).
-- Originally this INSERT ran here, but `role_permissions` / `role-cashier` are created
-- in later migrations (phase35 + spatie_rbac), which caused P3009 on fresh `migrate deploy`.
-- Kept as an empty migration to preserve history ordering.
